/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg__asset_free(a: number): void;
export function _asset_fromString(a: number, b: number): number;
export function _asset_new(a: number, b: number, c: number, d: number): number;
export function _asset_amount(a: number): number;
export function _asset_set_amount(a: number, b: number): void;
export function _asset_amountFloat(a: number): number;
export function _asset_set_amountFloat(a: number, b: number): void;
export function _asset_precision(a: number): number;
export function _asset_set_precision(a: number, b: number): void;
export function _asset_symbol(a: number, b: number): void;
export function _asset_set_symbol(a: number, b: number, c: number): void;
export function _asset_isUIA(a: number): number;
export function _asset_toString(a: number, b: number, c: number, d: number): void;
export function _asset__plus_num(a: number, b: number): number;
export function _asset__plus(a: number, b: number): number;
export function _asset__minus_num(a: number, b: number): number;
export function _asset__minus(a: number, b: number): number;
export function _asset__mul_num(a: number, b: number): number;
export function _asset__mul(a: number, b: number): number;
export function _asset__div_num(a: number, b: number): number;
export function _asset__div(a: number, b: number): number;
export function _asset_eq(a: number, b: number): number;
export function _asset_ne(a: number, b: number): number;
export function _asset_lt(a: number, b: number): number;
export function _asset_lte(a: number, b: number): number;
export function _asset_gt(a: number, b: number): number;
export function _asset_gte(a: number, b: number): number;
export function __wbg_streaminghandle_free(a: number): void;
export function stream_block_number(a: number, b: number): number;
export function aes256_decrypt(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export const __wbindgen_export_0: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hd59827e89d48352c(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
