name: test JS

on:
  push:
    paths:
      - 'golos-lib-js/**'
      
defaults:
  run:
    working-directory: golos-lib-js
      
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - run: yarn test
